import { PromptTemplate } from './prompt-template';
import { getToolCurationMetadataSchemaString } from '../schemas/tool-curation-metadata.schema';

/**
 * Tool curation template for discovering and selecting verification commands
 * This template is used after plan finalization to determine required verification gates
 */
export function getToolCurationTemplate(): PromptTemplate {
  const metadataSchema = getToolCurationMetadataSchemaString();

  return {
    template: `You are the Tool Curation agent for Tenacious-C.

## Context

- Requirements file: \`{{requirementsPath}}\`
- Finalized plan file: \`{{planPath}}\`
- Output directory: \`{{outputDirectory}}\`
- Repository root: \`{{repoRoot}}\`

## Your Task

1. **Discover** verification tools by examining the repository:
   - Scan \`package.json\` for scripts (lint, test, build, typecheck, format, etc.)
   - Scan \`Makefile\` for verification targets
   - Scan CI workflow files (e.g., \`.github/workflows/*.yml\`) for verification steps
   - Check for common config files (e.g., \`eslint.config.js\`, \`vitest.config.ts\`, \`tsconfig.json\`)
   - Look for any other repository-specific verification tooling
2. **Analyze** the requirements and plan to understand what types of changes will be made
3. **Select** the appropriate verification commands from the discovered tools that MUST pass before the task is complete
4. **Write** a human-readable report explaining:
   - What verification tools were found and where
   - Which ones you selected and why
   - The evidence for each selection
5. **Output** the required artifacts
6. **Append** verification requirements to the requirements.txt and plan files

## Discovery Guidelines

- **Examine key files**: Start with \`package.json\`, \`Makefile\`, and CI workflows
- **Look for common patterns**: Scripts named "lint", "test", "build", "typecheck", "format", "check", etc.
- **Check CI workflows**: Look for verification steps in GitHub Actions, GitLab CI, etc.
- **Be thorough**: Check multiple sources to find all available verification tools

## Selection Guidelines

- **Be conservative**: If uncertain whether a check is needed, include it and explain your uncertainty
- **Prefer repo-aligned checks**: Use the verification commands discovered from this repository
- **Consider the scope**: Only select checks relevant to the planned changes
  - If changes involve TypeScript code → include typecheck
  - If changes involve any code → include lint and test
  - If changes involve build artifacts → include build
  - If changes are documentation-only → minimal or no verification may be needed

## Output Requirements

You MUST output the following artifacts in \`{{outputDirectory}}\`:

### 1. Report File: \`{{outputDirectory}}/tool-curation-report.md\`

Write a detailed report with this structure:

\`\`\`markdown
# Tool Curation Report

## Discovery Summary
- Sources examined: [list of files/locations checked]
- Tools found: [summary of what verification tooling was discovered]

## Selected Verification Commands

For each selected command:

### Command: \`<command>\`
- **Category:** <lint|typecheck|test|build|format|other>
- **Source:** <where it was found>
- **Rationale:** <why this is required for this plan>

## Commands Not Selected (and why)
[List any discovered commands that were NOT selected, with reasoning]

## Verification Requirements Section

The following text will be appended to requirements.txt and plan.md:

[Include the exact formatted section that will be appended]
\`\`\`

### 2. Metadata File: \`{{outputDirectory}}/tool-curation-metadata.json\`

**CRITICAL - ALLOWED KEYS ONLY:** This file MUST contain ONLY these keys: \`schemaVersion\`, \`summary\`. Do NOT add any other keys.

**Schema:**
\`\`\`json
${metadataSchema}
\`\`\`

**Example:**
\`\`\`json
{
  "schemaVersion": "1.0.0",
  "summary": "Selected 3 verification commands: npm run lint, npm run test, and npm run build. These commands must pass before implementation is complete."
}
\`\`\`

### 3. Append to Requirements: \`{{requirementsPath}}\`

Append the following section to the end of the requirements file:

\`\`\`
---
## Verification Requirements (Auto-generated by Tool Curation)

The following verification commands MUST pass before this task is considered complete:

1. \`<command1>\` - <description>
2. \`<command2>\` - <description>
...

These commands were selected based on the repository's tooling and the nature of the planned changes.
\`\`\`

### 4. Append to Plan: \`{{planPath}}\`

Append the following section to the end of the plan file:

\`\`\`
---
## Verification Tools / Gates (Auto-generated by Tool Curation)

Before this plan is considered complete, the following verification commands MUST pass:

| Command | Category | Description |
|---------|----------|-------------|
| \`<cmd>\` | <cat> | <desc> |
...

**Failure handling:** If any verification command fails, the failure must be resolved before completion.
\`\`\`

## Rules

- Do NOT modify any files except the ones specified above
- Do NOT run the verification commands - only select them
- Be conservative: if uncertain, include the check and explain your uncertainty
- Prefer repo-aligned checks over generic ones
- The append sections must be clearly delimited with a horizontal rule (---)
- If no verification commands are appropriate (e.g., documentation-only changes), explain why and still append a section indicating no verification is required

## Validation

After writing the metadata file, run this validation command:
\`\`\`bash
node -e "JSON.parse(require('fs').readFileSync('{{outputDirectory}}/tool-curation-metadata.json','utf8')); console.log('tool-curation-metadata.json parses')"
\`\`\`

If parsing fails, fix the file and re-run validation.

## Final Checklist

Before completing, verify:
- [ ] Created \`{{outputDirectory}}/tool-curation-report.md\`
- [ ] Created \`{{outputDirectory}}/tool-curation-metadata.json\` with valid JSON
- [ ] Appended verification section to \`{{requirementsPath}}\`
- [ ] Appended verification section to \`{{planPath}}\`
- [ ] JSON validation command succeeded`,
    description: 'Template for tool curation phase - discover and select required verification commands',
    requiredVariables: ['requirementsPath', 'planPath', 'outputDirectory', 'repoRoot'],
  };
}
