/**
 * Integration Tests for Tool Curation Flow
 *
 * Tests the append artifact utilities used by AI agent output.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { MemoryFileSystem, createMemoryFileSystem } from '../../src/io/memory-file-system';
import {
  appendToFile,
  formatVerificationSectionForPlan,
  formatVerificationSectionForRequirements,
  VerificationCommandForFormat,
} from '../../src/io/append-artifact';

describe('Tool Curation Integration Tests', () => {
  let fileSystem: MemoryFileSystem;

  beforeEach(() => {
    fileSystem = createMemoryFileSystem('/repo');
  });

  describe('Requirements File Append Behavior', () => {
    it('should append verification section to requirements.txt', async () => {
      // Set up initial requirements
      await fileSystem.mkdir('/repo/.tenacious-c/test-run', true);
      const requirementsPath = '/repo/.tenacious-c/test-run/requirements.txt';
      const originalContent = `# Original Requirements

1. Implement feature X
2. Fix bug Y
3. Add tests for Z`;

      await fileSystem.writeFile(requirementsPath, originalContent);

      // Create verification commands
      const commands: VerificationCommandForFormat[] = [
        { command: 'npm run lint', category: 'lint', description: 'Run ESLint' },
        { command: 'npm run test', category: 'test', description: 'Run unit tests' },
      ];

      // Format and append
      const verificationSection = formatVerificationSectionForRequirements(commands);
      await appendToFile(
        requirementsPath,
        {
          delimiter: '---',
          content: verificationSection,
        },
        fileSystem
      );

      // Verify
      const result = await fileSystem.readFile(requirementsPath);
      expect(result.ok).toBe(true);
      if (result.ok) {
        // Original content preserved
        expect(result.value).toContain('# Original Requirements');
        expect(result.value).toContain('Implement feature X');
        expect(result.value).toContain('Fix bug Y');
        expect(result.value).toContain('Add tests for Z');

        // Verification section appended
        expect(result.value).toContain('## Verification Requirements');
        expect(result.value).toContain('Auto-generated by Tool Curation');
        expect(result.value).toContain('`npm run lint`');
        expect(result.value).toContain('`npm run test`');

        // Uses list format (not table)
        expect(result.value).toContain('1. `npm run lint`');
        expect(result.value).not.toContain('| Command |');
      }
    });

    it('should not duplicate verification section on multiple appends', async () => {
      await fileSystem.mkdir('/repo/.tenacious-c/test-run', true);
      const requirementsPath = '/repo/.tenacious-c/test-run/requirements.txt';
      await fileSystem.writeFile(requirementsPath, 'Original content');

      const commands: VerificationCommandForFormat[] = [
        { command: 'npm run test', category: 'test', description: 'Run tests' },
      ];

      const verificationSection = formatVerificationSectionForRequirements(commands);

      // First append
      await appendToFile(
        requirementsPath,
        { delimiter: '---', content: verificationSection },
        fileSystem
      );

      const afterFirst = await fileSystem.readFile(requirementsPath);
      expect(afterFirst.ok).toBe(true);

      // Count occurrences of verification header
      const countOccurrences = (str: string, pattern: string) =>
        (str.match(new RegExp(pattern, 'g')) || []).length;

      if (afterFirst.ok) {
        const firstCount = countOccurrences(
          afterFirst.value,
          '## Verification Requirements'
        );
        expect(firstCount).toBe(1);
      }
    });
  });

  describe('Plan File Append Behavior', () => {
    it('should append verification section to plan.md with table format', async () => {
      // Set up initial plan
      await fileSystem.mkdir('/repo/.tenacious-c/test-run', true);
      const planPath = '/repo/.tenacious-c/test-run/plan.md';
      const originalContent = `# Implementation Plan

## Phase 1: Setup
- Install dependencies
- Configure environment

## Phase 2: Implementation
- Create components
- Write business logic`;

      await fileSystem.writeFile(planPath, originalContent);

      // Create verification commands
      const commands: VerificationCommandForFormat[] = [
        { command: 'npm run lint', category: 'lint', description: 'Run ESLint' },
        { command: 'npm run typecheck', category: 'typecheck', description: 'Type check' },
        { command: 'npm run test', category: 'test', description: 'Run unit tests' },
      ];

      // Format and append
      const verificationSection = formatVerificationSectionForPlan(commands);
      await appendToFile(
        planPath,
        {
          delimiter: '---',
          content: verificationSection,
        },
        fileSystem
      );

      // Verify
      const result = await fileSystem.readFile(planPath);
      expect(result.ok).toBe(true);
      if (result.ok) {
        // Original content preserved
        expect(result.value).toContain('# Implementation Plan');
        expect(result.value).toContain('## Phase 1: Setup');
        expect(result.value).toContain('## Phase 2: Implementation');

        // Verification section appended with table format
        expect(result.value).toContain('## Verification Tools / Gates');
        expect(result.value).toContain('| Command | Category | Description |');
        expect(result.value).toContain('|---------|----------|-------------|');
        expect(result.value).toContain('| `npm run lint`');
        expect(result.value).toContain('| `npm run typecheck`');
        expect(result.value).toContain('| `npm run test`');
      }
    });

    it('should include failure handling instructions', async () => {
      await fileSystem.mkdir('/repo', true);
      const planPath = '/repo/plan.md';
      await fileSystem.writeFile(planPath, '# Plan');

      const commands: VerificationCommandForFormat[] = [
        { command: 'npm run test', category: 'test', description: 'Run tests' },
      ];

      const verificationSection = formatVerificationSectionForPlan(commands);
      await appendToFile(
        planPath,
        { delimiter: '---', content: verificationSection },
        fileSystem
      );

      const result = await fileSystem.readFile(planPath);
      expect(result.ok).toBe(true);
      if (result.ok) {
        expect(result.value).toContain('**Failure handling:**');
        expect(result.value).toContain('failure must be resolved');
      }
    });
  });
});
