/**
 * Tests for Append Artifact Utilities
 */

import { describe, it, expect } from 'vitest';
import { createMemoryFileSystem } from './memory-file-system';
import {
  appendToFile,
  formatVerificationSectionForPlan,
  formatVerificationSectionForRequirements,
  VerificationCommandForFormat,
} from './append-artifact';

describe('appendToFile', () => {
  it('should preserve original content and append new content', async () => {
    const fs = createMemoryFileSystem('/repo');
    await fs.mkdir('/repo', true);
    await fs.writeFile('/repo/test.txt', 'Original content here.');

    await appendToFile(
      '/repo/test.txt',
      {
        delimiter: '---',
        content: 'Appended content here.',
      },
      fs
    );

    const result = await fs.readFile('/repo/test.txt');
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toContain('Original content here.');
      expect(result.value).toContain('Appended content here.');
    }
  });

  it('should insert delimiter between original and new content', async () => {
    const fs = createMemoryFileSystem('/repo');
    await fs.mkdir('/repo', true);
    await fs.writeFile('/repo/test.txt', 'Line 1\nLine 2');

    await appendToFile(
      '/repo/test.txt',
      {
        delimiter: '---',
        content: 'New section',
      },
      fs
    );

    const result = await fs.readFile('/repo/test.txt');
    expect(result.ok).toBe(true);
    if (result.ok) {
      // Check that delimiter appears between original and new
      expect(result.value).toBe('Line 1\nLine 2\n\n---\nNew section');
    }
  });

  it('should support custom delimiters', async () => {
    const fs = createMemoryFileSystem('/repo');
    await fs.mkdir('/repo', true);
    await fs.writeFile('/repo/test.md', '# Document\n\nContent.');

    await appendToFile(
      '/repo/test.md',
      {
        delimiter: '<!-- VERIFICATION SECTION -->',
        content: '## Verification\n\n- Check 1\n- Check 2',
      },
      fs
    );

    const result = await fs.readFile('/repo/test.md');
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toContain('<!-- VERIFICATION SECTION -->');
      expect(result.value).toContain('## Verification');
    }
  });

  it('should throw error when file does not exist', async () => {
    const fs = createMemoryFileSystem('/repo');
    await fs.mkdir('/repo', true);

    await expect(
      appendToFile(
        '/repo/nonexistent.txt',
        {
          delimiter: '---',
          content: 'Content',
        },
        fs
      )
    ).rejects.toThrow('Failed to read file for append');
  });
});

describe('formatVerificationSectionForPlan', () => {
  const sampleCommands: VerificationCommandForFormat[] = [
    { command: 'npm run lint', category: 'lint', description: 'Run ESLint checks' },
    { command: 'npm run test', category: 'test', description: 'Run unit tests' },
    { command: 'npm run build', category: 'build', description: 'Build the project' },
  ];

  it('should return markdown table format with commands', () => {
    const result = formatVerificationSectionForPlan(sampleCommands);

    // Check for header
    expect(result).toContain('## Verification Tools / Gates');
    expect(result).toContain('Auto-generated by Tool Curation');

    // Check for table headers
    expect(result).toContain('| Command | Category | Description |');
    expect(result).toContain('|---------|----------|-------------|');

    // Check that all commands appear
    expect(result).toContain('`npm run lint`');
    expect(result).toContain('`npm run test`');
    expect(result).toContain('`npm run build`');

    // Check categories and descriptions
    expect(result).toContain('| lint |');
    expect(result).toContain('| test |');
    expect(result).toContain('| build |');
    expect(result).toContain('Run ESLint checks');
    expect(result).toContain('Run unit tests');
    expect(result).toContain('Build the project');
  });

  it('should include all commands in table rows', () => {
    const result = formatVerificationSectionForPlan(sampleCommands);

    // Each command should be in its own row with proper formatting
    expect(result).toContain('| `npm run lint` | lint | Run ESLint checks |');
    expect(result).toContain('| `npm run test` | test | Run unit tests |');
    expect(result).toContain('| `npm run build` | build | Build the project |');
  });

  it('should include failure handling footer', () => {
    const result = formatVerificationSectionForPlan(sampleCommands);

    expect(result).toContain('**Failure handling:**');
    expect(result).toContain('failure must be resolved');
  });

  it('should handle empty command list with appropriate message', () => {
    const result = formatVerificationSectionForPlan([]);

    expect(result).toContain('## Verification Tools / Gates');
    expect(result).toContain('No verification commands were selected');
    expect(result).toContain('documentation-only');
    expect(result).toContain('Manual review may still be appropriate');

    // Should NOT contain table headers when empty
    expect(result).not.toContain('| Command | Category | Description |');
  });

  it('should escape special characters in commands', () => {
    const commands: VerificationCommandForFormat[] = [
      { command: 'npm run lint:fix', category: 'lint', description: 'Fix linting issues' },
    ];

    const result = formatVerificationSectionForPlan(commands);
    expect(result).toContain('`npm run lint:fix`');
  });
});

describe('formatVerificationSectionForRequirements', () => {
  const sampleCommands: VerificationCommandForFormat[] = [
    { command: 'npm run lint', category: 'lint', description: 'Run ESLint checks' },
    { command: 'npm run test', category: 'test', description: 'Run unit tests' },
  ];

  it('should return list format (not table)', () => {
    const result = formatVerificationSectionForRequirements(sampleCommands);

    // Check for header
    expect(result).toContain('## Verification Requirements');
    expect(result).toContain('Auto-generated by Tool Curation');

    // Should use numbered list format, not table
    expect(result).toContain('1. `npm run lint`');
    expect(result).toContain('2. `npm run test`');

    // Should NOT contain table format
    expect(result).not.toContain('| Command |');
    expect(result).not.toContain('|---------|');
  });

  it('should include all commands with descriptions', () => {
    const result = formatVerificationSectionForRequirements(sampleCommands);

    expect(result).toContain('`npm run lint` - Run ESLint checks');
    expect(result).toContain('`npm run test` - Run unit tests');
  });

  it('should include footer about command selection', () => {
    const result = formatVerificationSectionForRequirements(sampleCommands);

    expect(result).toContain('selected based on the repository');
    expect(result).toContain('nature of the planned changes');
  });

  it('should handle empty command list with appropriate message', () => {
    const result = formatVerificationSectionForRequirements([]);

    expect(result).toContain('## Verification Requirements');
    expect(result).toContain('No verification commands were selected');
    expect(result).toContain('documentation-only');
    expect(result).toContain('Manual review may still be appropriate');

    // Should NOT contain numbered list when empty
    expect(result).not.toContain('1.');
  });

  it('should number commands correctly with multiple items', () => {
    const commands: VerificationCommandForFormat[] = [
      { command: 'npm run lint', category: 'lint', description: 'Lint' },
      { command: 'npm run test', category: 'test', description: 'Test' },
      { command: 'npm run build', category: 'build', description: 'Build' },
      { command: 'npm run typecheck', category: 'typecheck', description: 'Typecheck' },
    ];

    const result = formatVerificationSectionForRequirements(commands);

    expect(result).toContain('1. `npm run lint`');
    expect(result).toContain('2. `npm run test`');
    expect(result).toContain('3. `npm run build`');
    expect(result).toContain('4. `npm run typecheck`');
  });
});
