/**
 * Utilities for appending content to artifact files
 * Used by Tool Curation to append verification requirements to existing files
 */

import type { FileSystem } from '../types/file-system';

/**
 * Section to append to a file
 */
export interface AppendSection {
  /** Delimiter to separate from existing content (e.g., '---') */
  delimiter: string;
  /** Content to append after the delimiter */
  content: string;
}

/**
 * Append a delimited section to the end of a file
 *
 * @param filePath - Absolute path to the file
 * @param section - The section to append
 * @param fileSystem - File system interface
 */
export async function appendToFile(
  filePath: string,
  section: AppendSection,
  fileSystem: FileSystem
): Promise<void> {
  const result = await fileSystem.readFile(filePath);
  if (!result.ok) {
    throw new Error(`Failed to read file for append: ${result.error.message}`);
  }

  const existing = result.value;
  const appendText = `\n\n${section.delimiter}\n${section.content}`;

  const writeResult = await fileSystem.writeFile(filePath, existing + appendText);
  if (!writeResult.ok) {
    throw new Error(`Failed to write file after append: ${writeResult.error.message}`);
  }
}

/**
 * Verification command for formatting
 */
export interface VerificationCommandForFormat {
  command: string;
  category: string;
  description: string;
}

/**
 * Format verification commands for appending to plan.md (table format)
 *
 * @param commands - List of verification commands
 * @returns Formatted string ready to append
 */
export function formatVerificationSectionForPlan(
  commands: VerificationCommandForFormat[]
): string {
  if (commands.length === 0) {
    return `## Verification Tools / Gates (Auto-generated by Tool Curation)

No verification commands were selected for this plan. This may be because:
- The changes are documentation-only
- No relevant verification tooling was found in the repository
- The scope of changes does not require automated verification

**Note:** Manual review may still be appropriate.`;
  }

  const header = `## Verification Tools / Gates (Auto-generated by Tool Curation)

Before this plan is considered complete, the following verification commands MUST pass:

| Command | Category | Description |
|---------|----------|-------------|`;

  const rows = commands
    .map((c) => `| \`${c.command}\` | ${c.category} | ${c.description} |`)
    .join('\n');

  const footer = `

**Failure handling:** If any verification command fails, the failure must be resolved before completion.`;

  return header + '\n' + rows + footer;
}

/**
 * Format verification commands for appending to requirements.txt (list format)
 *
 * @param commands - List of verification commands
 * @returns Formatted string ready to append
 */
export function formatVerificationSectionForRequirements(
  commands: VerificationCommandForFormat[]
): string {
  if (commands.length === 0) {
    return `## Verification Requirements (Auto-generated by Tool Curation)

No verification commands were selected for this task. This may be because:
- The changes are documentation-only
- No relevant verification tooling was found in the repository
- The scope of changes does not require automated verification

Manual review may still be appropriate.`;
  }

  const header = `## Verification Requirements (Auto-generated by Tool Curation)

The following verification commands MUST pass before this task is considered complete:

`;

  const list = commands
    .map((c, i) => `${i + 1}. \`${c.command}\` - ${c.description}`)
    .join('\n');

  const footer = `

These commands were selected based on the repository's tooling and the nature of the planned changes.`;

  return header + list + footer;
}
